UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
	AS = as --32
	LD = ld
	LDFLAGS = -m elf_i386
	CC = gcc
	CFLAGS = -g -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce
	AR = ar
	STRIP = strip
	OBJCOPY = objecopy
	gcc_version = $(shell ls -l `which gcc` | tr '-' '\n' | tail -1)
endif

